# first invocation: resolve the binary while online
invoker.goals.1 = thriftc:resolve

# second invocation: compile in offline mode using the pre-fetched binary
invoker.goals.2 = -o generate-sources
invoker.debug.2 = true
