name: build-thriftc-jar

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: set up mise
        uses: jdx/mise-action@v4

      - name: build and install thriftc-jar
        run: mise run build-thriftc
